detectors:
  IrresponsibleModule:
    exclude:
      - AnotherRecordOne
      - RecordOne
      - RecordTwo
      - BasicRecord
      - BigStringRecord

  DuplicateMethodCall:
    exclude:
      - KeyVortex::Record#define_getter
      - KeyVortex::Record#define_setter
